#!/usr/bin/env bash
set -euo pipefail

ORANGE_PI_ENDPOINT="${ORANGE_PI_ENDPOINT:-http://192.168.1.30:4318}"
ORANGE_PI_TRACE_UI="${ORANGE_PI_TRACE_UI:-http://192.168.1.30:16686/trace}"
LOCAL_LOG="${PI_OTEL_LOCAL_LOG:-$HOME/.local/share/pi-opentelemetry/events.jsonl}"
SETTINGS="$HOME/.pi/agent/settings.json"
ENV_FILE="$HOME/.config/pi/telemetry.env"
PACKAGE='git:github.com/saphid/pi-opentelemetry'

mkdir -p "$(dirname "$ENV_FILE")" "$(dirname "$LOCAL_LOG")"
cat > "$ENV_FILE" <<EOF
# Pi OpenTelemetry unattended defaults.
# Generated by pi-opentelemetry/scripts/install-unattended.sh
export OTEL_EXPORTER_OTLP_ENDPOINT="$ORANGE_PI_ENDPOINT"
export OTEL_TRACE_UI_BASE_URL="$ORANGE_PI_TRACE_UI"
export PI_OTEL_LOCAL_LOG="$LOCAL_LOG"
EOF

if [[ -f "$HOME/.zshrc" ]] && ! grep -q 'source "$HOME/.config/pi/telemetry.env"' "$HOME/.zshrc"; then
  cat >> "$HOME/.zshrc" <<'EOF'

# Pi telemetry: unattended local + OTLP export
[ -f "$HOME/.config/pi/telemetry.env" ] && source "$HOME/.config/pi/telemetry.env"
EOF
fi

if command -v pi >/dev/null 2>&1; then
  if ! pi list 2>/dev/null | grep -q 'saphid/pi-opentelemetry'; then
    pi install "$PACKAGE"
  fi
elif [[ -f "$SETTINGS" ]] && ! grep -q 'saphid/pi-opentelemetry' "$SETTINGS"; then
  node -e 'const fs=require("fs"); const p=process.argv[1]; const pkg=process.argv[2]; const s=JSON.parse(fs.readFileSync(p,"utf8")); s.packages=s.packages||[]; if(!s.packages.some(x => (typeof x === "string" ? x : x && x.source) === pkg)) s.packages.push(pkg); fs.writeFileSync(p, JSON.stringify(s,null,2)+"\n");' "$SETTINGS" "$PACKAGE"
fi

cat <<EOF
Pi telemetry unattended setup complete.

Environment file: $ENV_FILE
Local log:        $LOCAL_LOG
OTLP endpoint:    $ORANGE_PI_ENDPOINT
Trace UI:         $ORANGE_PI_TRACE_UI
Package:          $PACKAGE

Restart shells / Pi sessions so ~/.zshrc picks up the environment.
EOF
